runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /_ah/mail/.+
  script: handle_incoming_email.app

inbound_services:
- mail

env_variables:
  DD_MAIL_CODE: "XXXXXXXXXXXXXXXXXXXXXXXXXX_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  USER_EMAIL: "user@email.com"
  BANK_EMAIL: "email@bank.com"